CC=gcc
CFLAGS=-Wall -g -std=c1x

all: maxemedia maxemedia2

maxemedia: maxemedia.c
	$(CC) $(CFLAGS) maxemedia.c -o maxemedia

maxemedia2: maxemedia2.c
	$(CC) $(CFLAGS) maxemedia2.c -o maxemedia2

clean:
	rm -rf maxemedia maxemedia2

